server:
  port: 8000
spring:
  application:
    name: catalog
  datasource:
    url: jdbc:postgresql://localhost:5432/db_bookstore_catalog
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: validate
flyway:
  enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  tracing:
    sampling:
      probability: 1.0
